#!/usr/bin/env python3
"""Inline web/ into one page, gzip it, and emit src/gw_ui_gz.h.

Every local <link rel="stylesheet" href> and <script src> in web/index.html
is replaced by its file's contents, in order - the frontend is plain
scripts sharing one global scope, so concatenation is all the "bundling"
it needs. Python stdlib only: PlatformIO already ships Python, so building
the firmware never needs Node.

  python3 tools/build_ui.py               # writes src/gw_ui_gz.h
  python3 tools/build_ui.py --out-gz X    # also writes the raw .gz (for GARNET_WEB_UI_FS)
  python3 tools/build_ui.py --check       # exit 1 if the header is stale

Output is deterministic (gzip mtime 0), so an unchanged UI gives a
byte-identical header and a stable ETag.
"""

import argparse
import gzip
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
HEADER = ROOT / "src" / "gw_ui_gz.h"


def inline(index: pathlib.Path) -> str:
    page = index.read_text(encoding="utf-8")

    def css(m):
        text = (index.parent / m.group(1)).read_text(encoding="utf-8")
        # Drop comments and indentation - ~25% of the stylesheet, zero risk.
        text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
        text = "\n".join(line.strip() for line in text.splitlines() if line.strip())
        return "<style>\n" + text + "\n</style>"

    def js(m):
        text = (index.parent / m.group(1)).read_text(encoding="utf-8")
        # A literal "</script" inside JS would end the inline block early.
        text = text.replace("</script", "<\\/script")
        return "<script>\n" + text + "\n</script>"

    page = re.sub(r"<!--.*?-->", "", page, flags=re.S)
    page = re.sub(r'<link rel="stylesheet" href="([^":]+)"\s*/?>', lambda m: css(m), page)
    page = re.sub(r'<script src="([^":]+)"></script>', lambda m: js(m), page)
    return page


def render_header(gz: bytes) -> str:
    etag = hashlib.sha256(gz).hexdigest()[:16]
    rows = []
    for i in range(0, len(gz), 20):
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in gz[i : i + 20]) + ",")
    body = "\n".join(rows)
    return (
        "#pragma once\n"
        "// GENERATED by tools/build_ui.py from web/ - do not edit by hand.\n"
        f"// {len(gz)} bytes gzipped.\n\n"
        "#include <cstddef>\n#include <cstdint>\n\n"
        f'static const char kGwUiEtag[] = "\\"{etag}\\"";\n'
        f"static const size_t kGwUiGzLen = {len(gz)};\n"
        "static const uint8_t kGwUiGz[] = {\n"
        f"{body}\n"
        "};\n"
    )


def build():
    page = inline(WEB / "index.html").encode("utf-8")
    gz = gzip.compress(page, compresslevel=9, mtime=0)
    return page, gz


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-gz", help="also write the gzipped page to this path")
    ap.add_argument("--check", action="store_true", help="fail if the header is out of date")
    args = ap.parse_args(argv)

    page, gz = build()
    header = render_header(gz)
    if args.check:
        current = HEADER.read_text() if HEADER.exists() else ""
        if current != header:
            print("gw_ui_gz.h is stale - run tools/build_ui.py", file=sys.stderr)
            return 1
        return 0
    # Only touch the file when it changes, so SCons doesn't rebuild the
    # server object on every build.
    if not HEADER.exists() or HEADER.read_text() != header:
        HEADER.write_text(header)
    if args.out_gz:
        pathlib.Path(args.out_gz).write_bytes(gz)
    print(f"garnet_web UI: {len(page)} bytes -> {len(gz)} bytes gzipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
