#include "gw_internal.h"

#include <cJSON.h>

#if defined(GARNET_WEB_OTA)
#include <esp_ota_ops.h>
#endif

#if defined(GARNET_WEB_UI_FS)
#include <FS.h>
#else
#include "gw_ui_gz.h" // generated by tools/build_ui.py from web/
#endif

// esp_http_server (bundled with ESP-IDF) rather than ESPAsyncWebServer:
// no third-party dependency, and it's the same server on every chip the
// Arduino 3.x core supports (ESP32, S3, C6, P4...). It runs one task and
// serves requests one at a time, which keeps the handlers simple - all
// API traffic is a few small JSON documents.
//
// Only four URI handlers are registered (GET /, GET /api/*, POST /api/*,
// plus the 404 hook for captive-portal probes); routing below that is a
// plain string match, which keeps us far from max_uri_handlers.

namespace {

httpd_handle_t server = nullptr;

constexpr size_t kMaxBody = 16 * 1024; // a settings backup is the largest body

#if defined(GARNET_WEB_UI_FS)
fs::FS *uiFs = nullptr;
constexpr const char *kUiPath = "/garnet_web/index.html.gz";
#endif

// ---- Helpers ---------------------------------------------------------------------

// req->uri includes the query string; routes only care about the path.
String pathOf(httpd_req_t *req) {
  String p = req->uri;
  int q = p.indexOf('?');
  return q < 0 ? p : p.substring(0, q);
}

esp_err_t sendJson(httpd_req_t *req, cJSON *json, const char *status = "200 OK") {
  httpd_resp_set_status(req, status);
  httpd_resp_set_type(req, "application/json");
  httpd_resp_set_hdr(req, "Cache-Control", "no-store");
  if (json == nullptr) {
    httpd_resp_set_status(req, "500 Internal Server Error");
    return httpd_resp_sendstr(req, "{\"ok\":false,\"error\":\"out of memory\"}");
  }
  char *text = cJSON_PrintUnformatted(json);
  cJSON_Delete(json);
  if (text == nullptr) {
    httpd_resp_set_status(req, "500 Internal Server Error");
    return httpd_resp_sendstr(req, "{\"ok\":false,\"error\":\"out of memory\"}");
  }
  esp_err_t err = httpd_resp_sendstr(req, text);
  cJSON_free(text);
  return err;
}

esp_err_t sendOk(httpd_req_t *req, bool reboot = false) {
  cJSON *o = cJSON_CreateObject();
  cJSON_AddBoolToObject(o, "ok", true);
  if (reboot) cJSON_AddBoolToObject(o, "reboot", true);
  return sendJson(req, o);
}

esp_err_t sendError(httpd_req_t *req, const char *status, const String &error,
                    const char *field = nullptr) {
  cJSON *o = cJSON_CreateObject();
  cJSON_AddBoolToObject(o, "ok", false);
  cJSON_AddStringToObject(o, "error", error.c_str());
  if (field) cJSON_AddStringToObject(o, "field", field);
  return sendJson(req, o, status);
}

// Reads and parses a JSON body. Null (and an error already sent) on failure.
cJSON *readJson(httpd_req_t *req) {
  if (req->content_len == 0 || req->content_len > kMaxBody) {
    sendError(req, "413 Payload Too Large", "body missing or too large");
    return nullptr;
  }
  char *buf = static_cast<char *>(malloc(req->content_len + 1));
  if (buf == nullptr) {
    sendError(req, "500 Internal Server Error", "out of memory");
    return nullptr;
  }
  size_t got = 0;
  while (got < req->content_len) {
    int r = httpd_req_recv(req, buf + got, req->content_len - got);
    if (r == HTTPD_SOCK_ERR_TIMEOUT) continue;
    if (r <= 0) {
      free(buf);
      return nullptr; // socket gone, nothing to reply to
    }
    got += r;
  }
  buf[got] = '\0';
  cJSON *json = cJSON_Parse(buf);
  free(buf);
  if (json == nullptr) sendError(req, "400 Bad Request", "invalid JSON");
  return json;
}

String jsonStr(const cJSON *obj, const char *key) {
  const cJSON *v = cJSON_GetObjectItemCaseSensitive(obj, key);
  return cJSON_IsString(v) ? String(v->valuestring) : String();
}

bool requireAuth(httpd_req_t *req) {
  if (gwAuthCheck(req)) return true;
  sendError(req, "401 Unauthorized", "login required");
  return false;
}

// "/api/group/display" with prefix "/api/group/" -> "display"
bool tail(const String &path, const char *prefix, String &out) {
  if (!path.startsWith(prefix)) return false;
  out = path.substring(strlen(prefix));
  return out.length() > 0;
}

const GsGroup *groupOr404(httpd_req_t *req, const String &id) {
  const GsGroup *g = gsFindGroup(id.c_str());
  if (g == nullptr) sendError(req, "404 Not Found", "no such group");
  return g;
}

// ---- GET ------------------------------------------------------------------------------

esp_err_t handleSession(httpd_req_t *req) {
  // Unauthenticated on purpose: the login screen needs the title/theme.
  cJSON *o = cJSON_CreateObject();
  cJSON_AddBoolToObject(o, "auth", gwAuthCheck(req));
  cJSON_AddStringToObject(o, "name", gwCfg.name);
  cJSON_AddStringToObject(o, "host", gwHostname().c_str());
  if (gwCfg.accent) cJSON_AddStringToObject(o, "accent", gwCfg.accent);
  if (gwCfg.logoSvg) cJSON_AddStringToObject(o, "logo", gwCfg.logoSvg);
  cJSON_AddBoolToObject(o, "portal", gwPortalActive());
#if defined(GARNET_WEB_OTA)
  cJSON_AddBoolToObject(o, "ota", true);
#endif
  return sendJson(req, o);
}

// Optional feature modules, each owning a /api/<name> prefix.
bool handleModules(httpd_req_t *req, const String &path, bool post, esp_err_t &err) {
  (void)req; (void)path; (void)post; (void)err;
#if defined(GARNET_WEB_TIME)
  if (gwTimeHandle(req, path, post, err)) return true;
#endif
#if defined(GARNET_WEB_LOG)
  if (gwLogHandle(req, path, post, err)) return true;
#endif
#if defined(GARNET_WEB_HW)
  if (gwHwHandle(req, path, post, err)) return true;
#endif
#if defined(GARNET_WEB_UART)
  if (gwUartHandle(req, path, post, err)) return true;
#endif
  return false;
}

esp_err_t handleApiGet(httpd_req_t *req) {
  String path = pathOf(req);
  if (path == "/api/session") return handleSession(req);
  if (!requireAuth(req)) return ESP_OK;

  String id;
#if defined(GARNET_WEB_FILES)
  if (path.startsWith("/api/fs")) return gwFilesHandle(req, path, false);
#endif
  esp_err_t modErr;
  if (handleModules(req, path, false, modErr)) return modErr;
  if (path == "/api/schema") return sendJson(req, static_cast<cJSON *>(gsSchemaJson()));
  if (tail(path, "/api/group/", id)) {
    const GsGroup *g = groupOr404(req, id);
    return g ? sendJson(req, static_cast<cJSON *>(gsValuesJson(*g))) : ESP_OK;
  }
  if (tail(path, "/api/live/", id)) {
    const GsGroup *g = groupOr404(req, id);
    return g ? sendJson(req, static_cast<cJSON *>(gsInfoJson(*g))) : ESP_OK;
  }
  if (path == "/api/backup") {
    String disp = String("attachment; filename=\"") + gwHostname() + "-settings.json\"";
    httpd_resp_set_hdr(req, "Content-Disposition", disp.c_str());
    return sendJson(req, static_cast<cJSON *>(gsBackupJson()));
  }
#if defined(GARNET_WEB_WIFI)
  if (path == "/api/wifi") return sendJson(req, static_cast<cJSON *>(gwWifiStatusJson()));
#endif
  return sendError(req, "404 Not Found", "no such endpoint");
}

// ---- POST -----------------------------------------------------------------------------

esp_err_t handleLogin(httpd_req_t *req) {
  cJSON *body = readJson(req);
  if (body == nullptr) return ESP_OK;
  String password = jsonStr(body, "password");
  cJSON_Delete(body);

  String token;
  uint32_t retryAfter = 0;
  if (!gwAuthLogin(password, token, retryAfter)) {
    if (retryAfter) {
      String s(retryAfter);
      httpd_resp_set_hdr(req, "Retry-After", s.c_str());
      return sendError(req, "429 Too Many Requests",
                       "Too many attempts, try again in " + s + " s");
    }
    return sendError(req, "401 Unauthorized", "Wrong password", "password");
  }
  // httpd_resp_set_hdr keeps the pointer, not a copy - the string must
  // outlive the send below, hence the local that lives until return.
  String cookie = "gw_s=" + token + "; Path=/; HttpOnly; SameSite=Strict";
  httpd_resp_set_hdr(req, "Set-Cookie", cookie.c_str());
  return sendOk(req);
}

esp_err_t handleGroupSave(httpd_req_t *req, const GsGroup &g) {
  cJSON *body = readJson(req);
  if (body == nullptr) return ESP_OK;
  GsSaveResult r = gsSaveGroup(g, body);
  cJSON_Delete(body);
  if (!r.ok) {
    const char *field = r.errorField >= 0 ? g.fields[r.errorField].key : nullptr;
    return sendError(req, "422 Unprocessable Entity", r.error, field);
  }
  gwDeferChanged(&g, r.changedMask);
  bool reboot = g.rebootOnSave && r.changedMask != 0;
  if (reboot) gwDeferReboot(1500);
  return sendOk(req, reboot);
}

#if defined(GARNET_WEB_OTA)
// Firmware update: the raw .bin as the request body, streamed straight
// into the inactive OTA slot - never buffered, so it works on chips with
// no PSRAM. esp_ota_end() verifies the image (magic, chip id, checksum /
// SHA) before the slot is made bootable; a wrong or truncated file leaves
// the running firmware untouched.
esp_err_t handleOta(httpd_req_t *req) {
  const esp_partition_t *slot = esp_ota_get_next_update_partition(nullptr);
  if (slot == nullptr) {
    return sendError(req, "500 Internal Server Error", "No OTA partition (check partition table)");
  }
  if (req->content_len == 0 || req->content_len > slot->size) {
    return sendError(req, "413 Payload Too Large",
                     "Firmware must be 1 B - " + gwFmtBytes(slot->size));
  }
  esp_ota_handle_t ota;
  // Sequential writes: erase as we go instead of erasing the whole slot
  // up front, which would stall this request for seconds before byte one.
  if (esp_ota_begin(slot, OTA_WITH_SEQUENTIAL_WRITES, &ota) != ESP_OK) {
    return sendError(req, "500 Internal Server Error", "Could not start update");
  }
  constexpr size_t kChunk = 4096;
  char *buf = static_cast<char *>(malloc(kChunk));
  if (buf == nullptr) {
    esp_ota_abort(ota);
    return sendError(req, "500 Internal Server Error", "out of memory");
  }
  size_t got = 0;
  bool ok = true;
  while (got < req->content_len) {
    int r = httpd_req_recv(req, buf, min(kChunk, req->content_len - got));
    if (r == HTTPD_SOCK_ERR_TIMEOUT) continue;
    if (r <= 0 || esp_ota_write(ota, buf, r) != ESP_OK) {
      ok = false;
      break;
    }
    got += r;
  }
  free(buf);
  if (!ok) {
    esp_ota_abort(ota);
    return sendError(req, "500 Internal Server Error", "Upload interrupted");
  }
  esp_err_t err = esp_ota_end(ota);
  if (err != ESP_OK) {
    return sendError(req, "422 Unprocessable Entity",
                     err == ESP_ERR_OTA_VALIDATE_FAILED ? "Not a valid firmware for this chip"
                                                        : "Update failed");
  }
  if (esp_ota_set_boot_partition(slot) != ESP_OK) {
    return sendError(req, "500 Internal Server Error", "Could not switch to new firmware");
  }
  log_i("garnet_web: OTA %u bytes to %s, rebooting", (unsigned)got, slot->label);
  gwDeferReboot(1500);
  return sendOk(req, true);
}
#endif

esp_err_t handleApiPost(httpd_req_t *req) {
  // Custom header = not a plain cross-site form/fetch (those can't set
  // one without a CORS preflight, which we never answer).
  char marker[4] = {};
  if (httpd_req_get_hdr_value_str(req, "X-GW", marker, sizeof(marker)) != ESP_OK ||
      strcmp(marker, "1") != 0) {
    return sendError(req, "403 Forbidden", "missing X-GW header");
  }

  String path = pathOf(req);
  if (path == "/api/login") return handleLogin(req);
  if (!requireAuth(req)) return ESP_OK;
#if defined(GARNET_WEB_OTA)
  if (path == "/api/ota") return handleOta(req);
#endif
#if defined(GARNET_WEB_FILES)
  if (path.startsWith("/api/fs/")) return gwFilesHandle(req, path, true);
#endif
  esp_err_t modErr;
  if (handleModules(req, path, true, modErr)) return modErr;

  if (path == "/api/logout") {
    gwAuthLogout(req);
    httpd_resp_set_hdr(req, "Set-Cookie", "gw_s=; Path=/; Max-Age=0; HttpOnly; SameSite=Strict");
    return sendOk(req);
  }

  String id;
  if (tail(path, "/api/group/", id)) {
    const GsGroup *g = groupOr404(req, id);
    return g ? handleGroupSave(req, *g) : ESP_OK;
  }

  if (tail(path, "/api/action/", id)) { // "<group>/<key>"
    int slash = id.indexOf('/');
    const GsGroup *g = slash > 0 ? gsFindGroup(id.substring(0, slash).c_str()) : nullptr;
    const GsField *f = g ? gsFindField(*g, id.substring(slash + 1).c_str()) : nullptr;
    if (f == nullptr || f->type != GsType::Button || f->action == nullptr) {
      return sendError(req, "404 Not Found", "no such action");
    }
    gwDeferAction(f);
    return sendOk(req);
  }

  if (path == "/api/password") {
    cJSON *body = readJson(req);
    if (body == nullptr) return ESP_OK;
    String why;
    bool ok = gwAuthChangePassword(jsonStr(body, "current"), jsonStr(body, "next"), why);
    cJSON_Delete(body);
    return ok ? sendOk(req) : sendError(req, "422 Unprocessable Entity", why);
  }

  if (path == "/api/restore") {
    cJSON *body = readJson(req);
    if (body == nullptr) return ESP_OK;
    String failed;
    int restored = gsRestoreJson(body, &failed);
    cJSON_Delete(body);
    if (restored == 0) {
      return sendError(req, "422 Unprocessable Entity",
                       failed.length() ? failed : String("nothing to restore"));
    }
    // Hooks don't run on restore - a reboot applies everything uniformly.
    gwDeferReboot(1500);
    cJSON *o = cJSON_CreateObject();
    cJSON_AddBoolToObject(o, "ok", true);
    cJSON_AddBoolToObject(o, "reboot", true);
    cJSON_AddNumberToObject(o, "restored", restored);
    if (failed.length()) cJSON_AddStringToObject(o, "failed", failed.c_str());
    return sendJson(req, o);
  }

#if defined(GARNET_WEB_WIFI)
  if (path == "/api/wifi/scan") {
    gwWifiRequestScan();
    return sendOk(req);
  }
  if (path == "/api/wifi/add" || path == "/api/wifi/forget") {
    cJSON *body = readJson(req);
    if (body == nullptr) return ESP_OK;
    String ssid = jsonStr(body, "ssid");
    String pass = jsonStr(body, "password");
    cJSON_Delete(body);
    if (path == "/api/wifi/forget") {
      return gwWifiForgetNet(ssid) ? sendOk(req) : sendError(req, "404 Not Found", "not saved");
    }
    if (ssid.length() == 0 || ssid.length() > 32) {
      return sendError(req, "422 Unprocessable Entity", "SSID must be 1-32 characters", "ssid");
    }
    if (pass.length() > 0 && (pass.length() < 8 || pass.length() > 63)) {
      return sendError(req, "422 Unprocessable Entity", "Password must be 8-63 characters",
                       "password");
    }
    if (!gwWifiAddNet(ssid, pass)) {
      return sendError(req, "500 Internal Server Error", "could not store network");
    }
    gwDeferReboot(1500);
    return sendOk(req, true);
  }
#endif

  return sendError(req, "404 Not Found", "no such endpoint");
}

// ---- UI + captive portal -----------------------------------------------------------

esp_err_t handleIndex(httpd_req_t *req) {
  httpd_resp_set_type(req, "text/html; charset=utf-8");
  httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
#if defined(GARNET_WEB_UI_FS)
  if (uiFs == nullptr) return httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "no UI fs");
  File f = uiFs->open(kUiPath, "r");
  if (!f) return httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "UI file missing");
  httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
  uint8_t chunk[1024];
  size_t n;
  while ((n = f.read(chunk, sizeof(chunk))) > 0) {
    if (httpd_resp_send_chunk(req, reinterpret_cast<const char *>(chunk), n) != ESP_OK) break;
  }
  f.close();
  return httpd_resp_send_chunk(req, nullptr, 0);
#else
  // ETag = build hash of the UI, so browsers revalidate cheaply and a
  // firmware update with a new UI is picked up immediately.
  char inm[24] = {};
  if (httpd_req_get_hdr_value_str(req, "If-None-Match", inm, sizeof(inm)) == ESP_OK &&
      strcmp(inm, kGwUiEtag) == 0) {
    httpd_resp_set_status(req, "304 Not Modified");
    return httpd_resp_send(req, nullptr, 0);
  }
  httpd_resp_set_hdr(req, "ETag", kGwUiEtag);
  httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
  return httpd_resp_send(req, reinterpret_cast<const char *>(kGwUiGz), kGwUiGzLen);
#endif
}

// Every unknown URL lands here - including the OS captive-portal probes
// (/generate_204, /hotspot-detect.html, /connecttest.txt, ...). While the
// setup AP is up, answering them with a redirect is what makes phones pop
// up the "Sign in to network" sheet showing our UI.
esp_err_t handleNotFound(httpd_req_t *req, httpd_err_code_t) {
  if (gwPortalActive()) {
    String location = "http://" + gwApIP().toString() + "/";
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", location.c_str());
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    return httpd_resp_send(req, nullptr, 0);
  }
  httpd_resp_set_status(req, "404 Not Found");
  return httpd_resp_sendstr(req, "Not found");
}

} // namespace

#if defined(GARNET_WEB_UI_FS)
void gwSetUiFs(fs::FS &fs) { uiFs = &fs; }
#endif

// ---- Shared helpers for feature modules -------------------------------------------

esp_err_t gwHttpJson(httpd_req_t *req, cJSON *json, const char *status) {
  return sendJson(req, json, status);
}
esp_err_t gwHttpOk(httpd_req_t *req) { return sendOk(req); }
esp_err_t gwHttpError(httpd_req_t *req, const char *status, const String &error) {
  return sendError(req, status, error);
}
cJSON *gwHttpReadJson(httpd_req_t *req) { return readJson(req); }
String gwHttpJsonStr(const cJSON *obj, const char *key) { return jsonStr(obj, key); }
int gwHttpJsonInt(const cJSON *obj, const char *key, int fallback) {
  const cJSON *v = cJSON_GetObjectItemCaseSensitive(obj, key);
  return cJSON_IsNumber(v) ? v->valueint : fallback;
}

String gwHttpQuery(httpd_req_t *req, const char *key) {
  size_t len = httpd_req_get_url_query_len(req);
  if (len == 0 || len > 1024) return "";
  char *q = static_cast<char *>(malloc(len + 1));
  if (q == nullptr) return "";
  String out;
  char raw[256];
  if (httpd_req_get_url_query_str(req, q, len + 1) == ESP_OK &&
      httpd_query_key_value(q, key, raw, sizeof(raw)) == ESP_OK) {
    for (const char *s = raw; *s; s++) { // %-decode (httpd leaves it encoded)
      if (*s == '+') out += ' ';
      else if (*s == '%' && isxdigit((unsigned char)s[1]) && isxdigit((unsigned char)s[2])) {
        char hex[3] = {s[1], s[2], 0};
        out += (char)strtol(hex, nullptr, 16);
        s += 2;
      } else out += *s;
    }
  }
  free(q);
  return out;
}

void gwServerBegin() {
  if (server != nullptr) return;
  httpd_config_t config = HTTPD_DEFAULT_CONFIG();
  config.server_port = gwCfg.port;
  config.ctrl_port = gwCfg.port + 32768; // unique per instance, well away from app ports
  config.uri_match_fn = httpd_uri_match_wildcard;
  // cJSON trees + String building for a whole group on this task's stack.
  config.stack_size = 8192;
  // Phones in captive-portal mode open many probe connections at once;
  // recycling the oldest socket beats refusing the one that matters.
  config.lru_purge_enable = true;
  config.max_uri_handlers = 6;

  if (httpd_start(&server, &config) != ESP_OK) {
    log_e("garnet_web: httpd_start failed on port %u", (unsigned)gwCfg.port);
    server = nullptr;
    return;
  }

  static const httpd_uri_t kRoutes[] = {
      {"/", HTTP_GET, handleIndex, nullptr},
      {"/index.html", HTTP_GET, handleIndex, nullptr},
      {"/api/*", HTTP_GET, handleApiGet, nullptr},
      {"/api/*", HTTP_POST, handleApiPost, nullptr},
  };
  for (const httpd_uri_t &route : kRoutes) httpd_register_uri_handler(server, &route);
  httpd_register_err_handler(server, HTTPD_404_NOT_FOUND, handleNotFound);
  log_i("garnet_web: web UI on port %u", (unsigned)gwCfg.port);
}
